package wasmcloud:provider-executor

interface provider-executor {
    run: func(command: string, payload: string|optional, post_args: string|optional) -> result<string, string>
}

world executor {
    export executor
}


